#pragma once

#include <cinttypes>

namespace Shipyard
{

#ifndef SHIP_MAX_VERTEX_BUFFERS
#define SHIP_MAX_VERTEX_BUFFERS 65535
#endif // #ifndef SHIP_MAX_VERTEX_BUFFERS

#ifndef SHIP_MAX_INDEX_BUFFERS
#define SHIP_MAX_INDEX_BUFFERS 65535
#endif // #ifndef SHIP_MAX_INDEX_BUFFERS

#ifndef SHIP_MAX_CONSTANT_BUFFERS
#define SHIP_MAX_CONSTANT_BUFFERS 262144
#endif // #ifndef SHIP_MAX_CONSTANT_BUFFERS

#ifndef SHIP_MAX_2D_TEXTURES
#define SHIP_MAX_2D_TEXTURES 1048576
#endif // #ifndef SHIP_MAX_2D_TEXTURES

#ifndef SHIP_MAX_RENDER_TARGETS
#define SHIP_MAX_RENDER_TARGETS 8192
#endif // #ifndef SHIP_MAX_RENDER_TARGETS

#ifndef SHIP_MAX_DEPTH_STENCIL_RENDER_TARGETS
#define SHIP_MAX_DEPTH_STENCIL_RENDER_TARGETS 1024
#endif // #ifndef SHIP_MAX_DEPTH_STENCIL_RENDER_TARGETS

#ifndef SHIP_MAX_VERTEX_SHADERS
#define SHIP_MAX_VERTEX_SHADERS 65535
#endif // #ifndef SHIP_MAX_VERTEX_SHADERS

#ifndef SHIP_MAX_PIXEL_SHADERS
#define SHIP_MAX_PIXEL_SHADERS 65535
#endif // #ifndef SHIP_MAX_PIXEL_SHADERS

#ifndef SHIP_MAX_ROOT_SIGNATURES
#define SHIP_MAX_ROOT_SIGNATURES 4096
#endif // #ifndef SHIP_MAX_ROOT_SIGNATURES

#ifndef SHIP_MAX_RENDER_PIPELINE_STATE_OBJECTS
#define SHIP_MAX_RENDER_PIPELINE_STATE_OBJECTS 16384
#endif // #ifndef SHIP_MAX_RENDER_PIPELINE_STATE_OBJECTS

#ifndef SHIP_MAX_DESCRIPTOR_SETS
#define SHIP_MAX_DESCRIPTOR_SETS 65535
#endif // #ifndef SHIP_MAX_DESCRIPTOR_SETS

#ifndef SHIP_COMMAND_LIST_HEAP_SIZE
#define SHIP_COMMAND_LIST_HEAP_SIZE 132072
#endif // #ifndef SHIP_COMMAND_LIST_HEAP_SIZE
}